version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      SQLALCHEMY_DATABASE_URL: "mysql://user:password@mysql/app"
      DB_HOST: "mysql"
      DB_NAME: "app"
      DB_USER: "user"
      DB_PASSWORD: "password"
    volumes:
      - ./api:/api

  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  game:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./game:/usr/share/nginx/html:ro

volumes:
  mysql_data:
